name: fleuron
description: Android client for Miniflux
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: assets/icon/icon.png
  adaptive_icon_foreground: assets/icon/adaptive.png
  adaptive_icon_background: '#ffffff'
  adaptive_icon_monochrome: assets/icon/monochrome.png
